#!/bin/bash

#Este script mostra a utilização de tomada de decisão.
#Este programa exibe no terminal uma mensagem informada no script.
#Desenvolvedor: Beatriz Ferraz, contato: biasferrazm@gmail.com
#Criação: 14/09/2022
#Modificação: 19/09/2022

echo "Digite 1 para somar"
echo "Digite 2 para subtrair"
echo "Digite 3 para multiplicar"
echo "Digite 4 para dividir"
read op
echo "Digite o valor de a"
read a
echo "Digite o valor de b"
read b

case $op in
1) echo "A soma de $a + $b é:" "$(($a+$b))";;
2) echo "A subatrção de $a - $b é:" "$(($a-$b))";;
3) echo "A multiplicação de $a * $b é:" "$(($a*$b))";;
4) echo "A divisão de $a / $b é:" "$(($a/$b))";;
esac
